CC = gcc 

CFLAGS = -Wall -Wextra -O2

all: mycat 
mycat: mycat.o main.O2
gcc -Wall -Wextra -O2 cat.o main.o -o mycat

mycat.o: mycat.catgcc -Wall -Wextra -O2 -c mycat.c

main.o: cat.c gcc -Wall -Wextra-O2 -c main.c 
clean: 
rm -f *.o mycat
